#pragma once

#include "NativeGameplayTags.h"

namespace GamePlayTag
{
	WARLEGEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Battle_Move);
	WARLEGEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Battle_Look);
	WARLEGEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Battle_EquipWeapon);
	WARLEGEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Battle_UnEquipWeapon);
	WARLEGEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Battle_LightAttack_Axe);
	WARLEGEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Battle_HeavyAttack_Axe);
	
	WARLEGEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	WARLEGEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	WARLEGEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	WARLEGEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	
	WARLEGEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);
	
	WARLEGEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_Attack);
	
	WARLEGEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	WARLEGEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnEquip_Axe);
	
	WARLEGEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	WARLEGEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_BaseDamage);
}
