#pragma once

#include "NativeGameplayTags.h"

namespace GamePlayTag
{
	WARLEGEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Battle_Move)
	WARLEGEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Battle_Look)
	WARLEGEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Battle_EquipWeapon)
	WARLEGEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Battle_UnEquipWeapon)
	
	WARLEGEND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);
}
